//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainApp2.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class block
    {
        public int block_id { get; set; }
        public Nullable<int> index_i { get; set; }
        public string nonce { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public string previous_hash { get; set; }
        public string hash { get; set; }
        public string data { get; set; }
        public string nft_nick { get; set; }
    
        public virtual blockchain blockchain { get; set; }
    }
}
