//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainApp2.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailkisibilgi
    {
        public string account_mail { get; set; }
        public string user_name { get; set; }
        public string user_surname { get; set; }
        public string user_pnumber { get; set; }
        public string user_nick { get; set; }
    }
}
