//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainApp2.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class nftbilgisi
    {
        public string user_nick { get; set; }
        public string nft_nick { get; set; }
        public string nft_creator { get; set; }
        public Nullable<int> nft_price { get; set; }
    }
}
